## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns=['EIN', 'NAME'], axis=1)

application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
application_type_counts = application_df['APPLICATION_TYPE'].value_counts()
application_type_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
cutoff_value = 500
application_types_to_replace = list(application_type_counts[application_type_counts < cutoff_value].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
classification_type_count = application_df['CLASSIFICATION'].value_counts()
classification_type_count

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_count_over_one = classification_type_count[classification_type_count > 1]
classification_count_over_one

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
cutoff_value = 1800
classifications_to_replace = list(classification_type_count[classification_type_count < cutoff_value].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [9]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df, dtype=int)
application_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [10]:
# Split our preprocessed data into our features and target arrays
X = application_df.drop(columns='IS_SUCCESSFUL').values
y = application_df['IS_SUCCESSFUL'].values


# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [11]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [12]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train[0])
hidden_nodes_layer1 =  15
hidden_nodes_layer2 = 15
hidden_nodes_layer3 = 15

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="LeakyReLU"))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer3, activation="LeakyReLU"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 15)                660

 dense_1 (Dense)             (None, 15)                240

 dense_2 (Dense)             (None, 15)                240

 dense_3 (Dense)             (None, 1)                 16

=================================================================
Total params: 1,156
Trainable params: 1,156
Non-trainable params: 0
_________________________________________________________________

In [13]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [14]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=200)

Epoch 1/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5862 - accuracy: 0.7085
Epoch 2/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5609 - accuracy: 0.7255
Epoch 3/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5563 - accuracy: 0.7279
Epoch 4/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5541 - accuracy: 0.7291
Epoch 5/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5530 - accuracy: 0.7291
Epoch 6/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5520 - accuracy: 0.7290
Epoch 7/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5512 - accuracy: 0.7301
Epoch 8/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5509 - accuracy: 0.7283
Epoch 9/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5500 - accuracy: 0.7297
Epoch 10/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5496 - accuracy: 0.7309
Epoch 11/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5491 - accuracy: 0.7310
Epoch 12/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5486 - accuracy: 0.7318
Epoch 13/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5483 - accuracy: 0.7327
Epoch 14/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5480 - accuracy: 0.7317
Epoch 15/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5479 - accuracy: 0.7315
Epoch 16/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5473 - accuracy: 0.7326
Epoch 17/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5469 - accuracy: 0.7322
Epoch 18/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5470 - accuracy: 0.7319
Epoch 19/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5467 - accuracy: 0.7328
Epoch 20/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5463 - accuracy: 0.7324
Epoch 21/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5462 - accuracy: 0.7326
Epoch 22/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5456 - accuracy: 0.7338
Epoch 23/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5457 - accuracy: 0.7323
Epoch 24/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5455 - accuracy: 0.7329
Epoch 25/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5453 - accuracy: 0.7334
Epoch 26/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5451 - accuracy: 0.7340
Epoch 27/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5451 - accuracy: 0.7341
Epoch 28/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5447 - accuracy: 0.7338
Epoch 29/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5446 - accuracy: 0.7336
Epoch 30/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5442 - accuracy: 0.7348
Epoch 31/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5444 - accuracy: 0.7333
Epoch 32/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5444 - accuracy: 0.7332
Epoch 33/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5435 - accuracy: 0.7353
Epoch 34/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5443 - accuracy: 0.7340
Epoch 35/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5436 - accuracy: 0.7348
Epoch 36/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5436 - accuracy: 0.7347
Epoch 37/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5433 - accuracy: 0.7344
Epoch 38/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5434 - accuracy: 0.7337
Epoch 39/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5431 - accuracy: 0.7334
Epoch 40/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5428 - accuracy: 0.7344
Epoch 41/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5430 - accuracy: 0.7334
Epoch 42/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5430 - accuracy: 0.7347
Epoch 43/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5427 - accuracy: 0.7345
Epoch 44/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5430 - accuracy: 0.7353
Epoch 45/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5427 - accuracy: 0.7348
Epoch 46/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5426 - accuracy: 0.7362
Epoch 47/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5426 - accuracy: 0.7355
Epoch 48/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5426 - accuracy: 0.7343
Epoch 49/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5422 - accuracy: 0.7359
Epoch 50/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5424 - accuracy: 0.7346
Epoch 51/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5422 - accuracy: 0.7349
Epoch 52/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5425 - accuracy: 0.7352
Epoch 53/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5425 - accuracy: 0.7352
Epoch 54/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5421 - accuracy: 0.7360
Epoch 55/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5417 - accuracy: 0.7359
Epoch 56/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5418 - accuracy: 0.7352
Epoch 57/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5419 - accuracy: 0.7365
Epoch 58/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5418 - accuracy: 0.7355
Epoch 59/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5416 - accuracy: 0.7362
Epoch 60/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5422 - accuracy: 0.7359
Epoch 61/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5415 - accuracy: 0.7355
Epoch 62/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5419 - accuracy: 0.7352
Epoch 63/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5413 - accuracy: 0.7349
Epoch 64/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5415 - accuracy: 0.7360
Epoch 65/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5414 - accuracy: 0.7360
Epoch 66/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5413 - accuracy: 0.7364
Epoch 67/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5410 - accuracy: 0.7371
Epoch 68/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5416 - accuracy: 0.7359
Epoch 69/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5415 - accuracy: 0.7358
Epoch 70/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5413 - accuracy: 0.7356
Epoch 71/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5412 - accuracy: 0.7353
Epoch 72/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5411 - accuracy: 0.7350
Epoch 73/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5410 - accuracy: 0.7358
Epoch 74/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5408 - accuracy: 0.7353
Epoch 75/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5407 - accuracy: 0.7364
Epoch 76/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5411 - accuracy: 0.7369
Epoch 77/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5410 - accuracy: 0.7350
Epoch 78/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5410 - accuracy: 0.7361
Epoch 79/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5408 - accuracy: 0.7363
Epoch 80/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5410 - accuracy: 0.7362
Epoch 81/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5407 - accuracy: 0.7369
Epoch 82/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5411 - accuracy: 0.7353
Epoch 83/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5404 - accuracy: 0.7363
Epoch 84/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5407 - accuracy: 0.7367
Epoch 85/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5407 - accuracy: 0.7360
Epoch 86/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5407 - accuracy: 0.7377
Epoch 87/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5405 - accuracy: 0.7362
Epoch 88/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5404 - accuracy: 0.7370
Epoch 89/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5405 - accuracy: 0.7358
Epoch 90/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5405 - accuracy: 0.7361
Epoch 91/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5404 - accuracy: 0.7364
Epoch 92/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5407 - accuracy: 0.7353
Epoch 93/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5404 - accuracy: 0.7358
Epoch 94/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5406 - accuracy: 0.7358
Epoch 95/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5401 - accuracy: 0.7367
Epoch 96/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5401 - accuracy: 0.7363
Epoch 97/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5401 - accuracy: 0.7363
Epoch 98/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5402 - accuracy: 0.7364
Epoch 99/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5400 - accuracy: 0.7350
Epoch 100/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5403 - accuracy: 0.7365
Epoch 101/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5406 - accuracy: 0.7366
Epoch 102/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5398 - accuracy: 0.7368
Epoch 103/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5398 - accuracy: 0.7367
Epoch 104/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5400 - accuracy: 0.7360
Epoch 105/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5398 - accuracy: 0.7359
Epoch 106/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5397 - accuracy: 0.7367
Epoch 107/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5401 - accuracy: 0.7376
Epoch 108/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5395 - accuracy: 0.7385
Epoch 109/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5395 - accuracy: 0.7370
Epoch 110/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5399 - accuracy: 0.7370
Epoch 111/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5403 - accuracy: 0.7368
Epoch 112/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5394 - accuracy: 0.7361
Epoch 113/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5403 - accuracy: 0.7368
Epoch 114/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5396 - accuracy: 0.7370
Epoch 115/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5397 - accuracy: 0.7362
Epoch 116/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5395 - accuracy: 0.7376
Epoch 117/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5392 - accuracy: 0.7369
Epoch 118/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5397 - accuracy: 0.7368
Epoch 119/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5395 - accuracy: 0.7374
Epoch 120/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5398 - accuracy: 0.7378
Epoch 121/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5394 - accuracy: 0.7373
Epoch 122/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5396 - accuracy: 0.7383
Epoch 123/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5395 - accuracy: 0.7366
Epoch 124/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5398 - accuracy: 0.7373
Epoch 125/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5393 - accuracy: 0.7379
Epoch 126/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5395 - accuracy: 0.7376
Epoch 127/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5395 - accuracy: 0.7370
Epoch 128/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5391 - accuracy: 0.7359
Epoch 129/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5389 - accuracy: 0.7384
Epoch 130/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5394 - accuracy: 0.7377
Epoch 131/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5393 - accuracy: 0.7383
Epoch 132/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5391 - accuracy: 0.7389
Epoch 133/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5392 - accuracy: 0.7377
Epoch 134/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5394 - accuracy: 0.7373
Epoch 135/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5391 - accuracy: 0.7362
Epoch 136/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5391 - accuracy: 0.7372
Epoch 137/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5387 - accuracy: 0.7376
Epoch 138/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5389 - accuracy: 0.7378
Epoch 139/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5392 - accuracy: 0.7381
Epoch 140/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5391 - accuracy: 0.7374
Epoch 141/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5389 - accuracy: 0.7371
Epoch 142/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5389 - accuracy: 0.7379
Epoch 143/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5389 - accuracy: 0.7374
Epoch 144/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5388 - accuracy: 0.7374
Epoch 145/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5389 - accuracy: 0.7379
Epoch 146/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5389 - accuracy: 0.7370
Epoch 147/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5389 - accuracy: 0.7372
Epoch 148/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5389 - accuracy: 0.7371
Epoch 149/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5388 - accuracy: 0.7383
Epoch 150/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5387 - accuracy: 0.7382
Epoch 151/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5389 - accuracy: 0.7379
Epoch 152/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5388 - accuracy: 0.7380
Epoch 153/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5390 - accuracy: 0.7371
Epoch 154/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5386 - accuracy: 0.7364
Epoch 155/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5388 - accuracy: 0.7369
Epoch 156/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5386 - accuracy: 0.7372
Epoch 157/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5388 - accuracy: 0.7372
Epoch 158/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5388 - accuracy: 0.7375
Epoch 159/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5388 - accuracy: 0.7385
Epoch 160/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5386 - accuracy: 0.7378
Epoch 161/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5384 - accuracy: 0.7378
Epoch 162/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5388 - accuracy: 0.7372
Epoch 163/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5386 - accuracy: 0.7381
Epoch 164/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5384 - accuracy: 0.7377
Epoch 165/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5384 - accuracy: 0.7386
Epoch 166/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5386 - accuracy: 0.7381
Epoch 167/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5385 - accuracy: 0.7380
Epoch 168/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5386 - accuracy: 0.7372
Epoch 169/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5383 - accuracy: 0.7374
Epoch 170/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5383 - accuracy: 0.7376
Epoch 171/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5381 - accuracy: 0.7384
Epoch 172/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5387 - accuracy: 0.7371
Epoch 173/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5384 - accuracy: 0.7378
Epoch 174/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5385 - accuracy: 0.7377
Epoch 175/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5387 - accuracy: 0.7361
Epoch 176/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5383 - accuracy: 0.7379
Epoch 177/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5382 - accuracy: 0.7381
Epoch 178/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5383 - accuracy: 0.7379
Epoch 179/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5383 - accuracy: 0.7376
Epoch 180/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5383 - accuracy: 0.7383
Epoch 181/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5381 - accuracy: 0.7388
Epoch 182/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5381 - accuracy: 0.7393
Epoch 183/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5383 - accuracy: 0.7378
Epoch 184/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5384 - accuracy: 0.7374
Epoch 185/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5378 - accuracy: 0.7377
Epoch 186/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5383 - accuracy: 0.7385
Epoch 187/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5378 - accuracy: 0.7389
Epoch 188/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5379 - accuracy: 0.7391
Epoch 189/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5380 - accuracy: 0.7383
Epoch 190/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5385 - accuracy: 0.7379
Epoch 191/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5377 - accuracy: 0.7383
Epoch 192/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5379 - accuracy: 0.7378
Epoch 193/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5381 - accuracy: 0.7376
Epoch 194/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5377 - accuracy: 0.7383
Epoch 195/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5379 - accuracy: 0.7388
Epoch 196/200

In [15]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5574 - accuracy: 0.7262 - 536ms/epoch - 2ms/step
Loss: 0.5574018359184265, Accuracy: 0.7261807322502136

In [16]:
# Export our model to HDF5 file
nn.save("./Resources/AlphabetSoupCharity_Optimization.h5")

ImportError: `save_model()` using h5 format requires h5py. Could not import h5py.